const navLinks = document.getElementById("navLinks");
const menuToggle = document.querySelector(".menu-toggle");
const languageButtons = document.querySelectorAll("[data-lang-switch]");
const caseFilterButtons = document.querySelectorAll(".case-filter-button");
const mentorFilterButtons = document.querySelectorAll(".mentor-filter-button");
const consultationForm = document.getElementById("consultationForm");
const formMessage = document.getElementById("formMessage");
const formPageUrl = document.getElementById("formPageUrl");
const formLanguage = document.getElementById("formLanguage");
const englishTextMap = {
  "主导航": "Primary navigation",
  "RAIN EDUCATION 首页": "RAIN EDUCATION home",
  "打开导航菜单": "Open navigation menu",
  "首页": "Home",
  "品牌简介": "About",
  "核心项目": "Core Programmes",
  "升学路径": "Pathway",
  "成功案例": "Success Cases",
  "导师团队": "Mentors",
  "预约咨询": "Enquire",
  "页面章节导航": "Page section navigation",
  "页脚导航": "Footer navigation",
  "Rain Education 首屏横幅": "Rain Education hero banner",
  "Rain Education 品牌简介": "Rain Education introduction",
  "Rain Education 核心数据": "Rain Education key metrics",
  "为什么选择 Rain Education": "Why Rain Education",
  "核心服务项目": "Core service programmes",
  "Rain Education 升学流程": "Rain Education admissions pathway",
  "家长决策中心": "Parent decision center",
  "信任中心": "Trust center",
  "常见问题": "Frequently Asked Questions",
  "Enquire Today 咨询表单": "Enquire Today form",
  "预约咨询快捷入口": "Quick enquiry shortcut",
  "以香港为起点 通往世界名校": "From Hong Kong to Global Top Universities",
  "以香港为起点": "From Hong Kong",
  "通往世界名校": "To Global Top Universities",
  "以长期规划，管理每一次升学选择": "Managing every admissions decision through long-term planning",
  "Rain Education 立足香港，为学生提供从背景诊断、路径设计、GPA 管理、申请执行到入学后发展的长期升学管理。我们不只关注一次申请结果，更关注学生未来数年的学术路径与成长空间。": "Based in Hong Kong, Rain Education provides long-term admissions management from background diagnosis, pathway design and GPA management to application execution and post-enrollment development. We focus not only on one application result, but on the student's academic path and growth space over the next several years.",
  "预约升学评估": "Book an admissions assessment",
  "了解核心项目": "Explore core programmes",
  "先看清学生条件，再设计可执行的升学路径": "First understand the student's profile, then design an executable admissions pathway",
  "我们结合学生的学术表现、院校政策、家庭目标与长期发展，建立清晰、可执行、可持续复盘的升学方案。": "We combine academic performance, university policies, family goals and long-term development to build clear, executable and reviewable admissions plans.",
  "教育咨询经验": "Years of education consulting",
  "学生案例": "Student cases",
  "香港八大名校升学率": "Hong Kong top-eight progression rate",
  "香港本地大学本科升学率": "Hong Kong local undergraduate progression rate",
  "香港前五名校升学率": "Hong Kong top-five university progression rate",
  "数据展示基于既有服务与案例统计，具体申请结果受学生背景、年度政策、材料质量及正式服务协议影响。": "Figures are based on previous services and case statistics. Individual outcomes depend on student background, annual policies, material quality and the formal service agreement.",
  "真正有效的升学规划，始于准确判断，成于持续管理": "Effective admissions planning begins with accurate judgement and succeeds through sustained management",
  "我们把香港本地升学制度、GPA 管理、背景提升、导师辅导与家庭决策支持整合成一套长期升学战略，而不是只完成一次申请递交。": "We integrate Hong Kong progression systems, GPA management, profile building, mentor coaching and family decision support into a long-term admissions strategy, rather than simply submitting one application.",
  "香港本地升学路径研究": "Hong Kong pathway research",
  "理解副学士、高级文凭、本科直申、港八衔接与多地联申的真实门槛。": "We interpret the real thresholds across associate degree, higher diploma, direct undergraduate admission, HK top-eight progression and multi-region applications.",
  "长期 GPA 管理": "Long-term GPA management",
  "把课程选择、作业、考试、学术写作和阶段反馈纳入同一个管理节奏。": "Course choices, assignments, exams, academic writing and stage reviews are managed in one rhythm.",
  "学术背景提升": "Academic profile building",
  "围绕目标专业积累科研、竞赛、实习、阅读和文书素材，而非堆砌活动。": "Research, competitions, internships, reading and essay material are built around the target subject rather than accumulated randomly.",
  "导师体系": "Mentor system",
  "按学科方向、申请阶段和学术短板匹配导师，与顾问方案同步推进。": "Mentors are matched by subject, application stage and academic gaps, then aligned with the advisor's plan.",
  "家长沟通与决策支持": "Parent communication and decision support",
  "向家长讲清楚时间、风险、费用、选择和责任边界，减少重大决策焦虑。": "We explain timing, risk, costs, options and responsibility boundaries clearly to parents, reducing anxiety around major choices.",
  "全球名校申请策略": "Global top university strategy",
  "覆盖香港、英国 G5、新加坡、美国、澳洲、加拿大及全球 QS Top 100 路径。": "Covering Hong Kong, UK G5, Singapore, the United States, Australia, Canada and global QS Top 100 pathways.",
  "九个核心项目，覆盖从高考后到全球名校的完整升学周期": "Nine core programmes covering the full cycle from post-Gaokao planning to global top universities",
  "每个服务都先回答三件事：学生是否适合、核心风险在哪里、Rain Education 如何把方案落到可跟进的任务上。": "Each service first answers three questions: whether the student is suitable, where the core risk lies, and how Rain Education turns the plan into trackable tasks.",
  "港八副学士 2+2+1 名校跃升计划": "HK top-eight associate degree 2+2+1 progression plan",
  "港九大本硕连读精英规划计划": "Hong Kong Nine Universities Bachelor–Master Elite Planning Programme",
  "香港本科申请": "Hong Kong undergraduate applications",
  "香港研究生 / 硕士申请": "Hong Kong postgraduate / master's applications",
  "英国 G5 申请": "UK G5 applications",
  "新加坡申请": "Singapore applications",
  "GPA 管理与背景提升": "GPA management and profile building",
  "国际名校申请规划": "Global top university application planning",
  "长期学业与职业发展规划": "Long-term academic and career development planning",
  "适合学生": "Suitable for",
  "核心问题": "Core issue",
  "解决方案": "Solution",
  "我们提供": "We provide",
  "高考后、国际课程或成绩未达理想本科线的学生。": "Post-Gaokao, international curriculum or students below their ideal undergraduate threshold.",
  "如何用副学士阶段重新建立 GPA 与本科衔接机会。": "How to rebuild GPA and undergraduate progression opportunities through the associate degree stage.",
  "副学士申请、入学适应、选课策略、GPA 管理、本科转入节奏。": "Associate degree applications, enrollment transition, course selection, GPA management and undergraduate transfer timing.",
  "背景诊断、院校梯度、材料管理、导师辅导与家长复盘。": "Background diagnosis, university tiering, materials management, mentor coaching and parent reviews.",
  "预约港八路径评估": "Assess the HK top-eight pathway",
  "希望把副学位、本科、实习与研究生升学连续规划的家庭。": "Families seeking continuous planning across sub-degree, undergraduate study, internships and postgraduate progression.",
  "单次申请无法覆盖入学后 GPA、背景和下一阶段升学。": "A single application cannot cover post-enrollment GPA, profile building and the next stage of progression.",
  "建立本科入读、学术表现、背景提升、就业实习与研究生申请时间线。": "Build a timeline for undergraduate enrollment, academic performance, profile building, internships and postgraduate applications.",
  "阶段规划、GPA 管理、背景提升、本科及研究生衔接、家长阶段复盘。": "Stage planning, GPA management, profile building, undergraduate and postgraduate progression, and parent stage reviews.",
  "本计划以长期学术规划、过程管理和申请支持为核心，不构成任何院校录取承诺；具体服务与责任边界以正式协议为准。": "This plan centers on long-term academic planning, process management and application support. It does not constitute any university admission promise; service scope and responsibility boundaries are subject to the formal agreement.",
  "咨询本硕路径": "Discuss the undergraduate-to-master's path",
  "高考生、DSE、A-Level、IB/AP 及其他国际课程学生。": "Gaokao, DSE, A-Level, IB/AP and other international curriculum students.",
  "如何在专业选择、院校梯度、材料与面试之间建立更匹配学生背景的申请组合。": "How to build an application combination across subject choice, university tiering, materials and interviews that better fits the student's background.",
  "本科直申、专业定位、文书材料、面试准备与多地联申。": "Direct undergraduate applications, subject positioning, essays, interview preparation and multi-region applications.",
  "香港本科政策解读、时间线管理、材料审核与录取后安排。": "Hong Kong undergraduate policy interpretation, timeline management, material review and post-offer arrangements.",
  "预约本科评估": "Assess undergraduate options",
  "本科在读、本科毕业、低 GPA 或跨专业申请学生。": "Current undergraduates, graduates, low-GPA and cross-discipline applicants.",
  "背景分散、专业摇摆、材料缺乏清晰申请叙事。": "Scattered background, uncertain subject positioning and materials lacking a clear application narrative.",
  "院校定位、专业匹配、简历、PS、推荐信、面试与补件跟进。": "University positioning, subject fit, CV, personal statement, recommendation letters, interviews and follow-up materials.",
  "香港、英国、新加坡及全球研究生方向联合规划。": "Joint planning for Hong Kong, UK, Singapore and global postgraduate directions.",
  "预约研究生评估": "Assess postgraduate options",
  "目标牛津、剑桥、IC、UCL、LSE 及高竞争专业学生。": "Students targeting Oxford, Cambridge, IC, UCL, LSE and highly competitive subjects.",
  "不只是成绩，还需要学科深度、笔试、面试与学术表达。": "Beyond grades, students need subject depth, admissions tests, interviews and academic expression.",
  "阅读清单、文书策略、MAT/STEP/TMUA 等笔试与模拟面试。": "Reading lists, essay strategy, MAT/STEP/TMUA-style tests and mock interviews.",
  "牛剑/G5 导师匹配、学术论证训练与申请材料统筹。": "Oxbridge/G5 mentor matching, academic argument training and application materials coordination.",
  "规划 G5 申请": "Plan a G5 application",
  "目标 NUS、NTU 及亚洲高竞争本科、研究生项目的学生。": "Students targeting NUS, NTU and competitive undergraduate or postgraduate programmes in Asia.",
  "新加坡方向重视专业匹配、学术能力与材料精准度。": "Singapore applications place strong emphasis on subject fit, academic ability and precise materials.",
  "院校专业清单、文书策略、面试准备、香港/英国联申备选。": "Programme lists, essay strategy, interview preparation and Hong Kong/UK backup combinations.",
  "跨地区时间线协调与录取后入学决策支持。": "Cross-region timeline coordination and post-offer enrollment decision support.",
  "咨询新加坡方向": "Discuss Singapore options",
  "副学士、本科在读、低 GPA、需要长期学术跟进的学生。": "Associate degree students, undergraduates, low-GPA students and those needing long-term academic follow-up.",
  "成绩曲线、课程选择、薄弱科目和背景材料会共同影响申请。": "Grade trends, course choices, weak subjects and profile materials jointly affect applications.",
  "课程辅导、作业与论文节点、选课策略、科研/竞赛/实习规划。": "Course coaching, assignment and paper milestones, course selection, research, competitions and internships.",
  "导师辅导、阶段复盘、家长沟通与下一阶段升学衔接。": "Mentor coaching, stage reviews, parent communication and next-stage progression.",
  "预约 GPA 诊断": "Book a GPA diagnosis",
  "希望同时比较香港、英国、新加坡、美国、澳洲、加拿大路径的学生。": "Students comparing Hong Kong, UK, Singapore, US, Australia and Canada pathways.",
  "不同地区评估标准不同，容易出现材料重复、节奏混乱和定位失真。": "Different regions assess differently, creating risks of duplicated materials, timing confusion and distorted positioning.",
  "地区组合、院校梯度、专业定位、材料适配和申请时间线统筹。": "Destination combinations, university tiering, subject positioning, material adaptation and application timeline coordination.",
  "以学生长期目标为中心，建立多地申请组合与风险备选。": "Build multi-region application combinations and backup plans around the student's long-term goals.",
  "规划全球名校路径": "Plan a global top university pathway",
  "希望把升学、GPA、实习、科研、职业方向与身份选择连续管理的家庭。": "Families seeking continuous management across admissions, GPA, internships, research, career direction and identity-related choices.",
  "只看下一次申请，容易忽视入学后的成绩表现和职业路径。": "Focusing only on the next application can neglect post-enrollment performance and career pathway.",
  "年度目标、课程选择、能力建设、实习科研与下一阶段申请路线图。": "Annual goals, course choices, capability building, internships, research and the next-stage application roadmap.",
  "顾问、导师与家庭定期复盘，把短期申请放入长期成长框架。": "Advisors, mentors and families review regularly, placing short-term applications within a long-term growth framework.",
  "咨询长期规划": "Discuss long-term planning",
  "从第一次评估到录取与入学，所有步骤都应可追踪": "From first assessment to admission and enrollment, every step should be trackable",
  "背景诊断": "Background diagnosis",
  "路径设计": "Pathway design",
  "GPA 与学术能力管理": "GPA and academic capability management",
  "文书与材料": "Essays and materials",
  "申请与面试": "Applications and interviews",
  "录取与入学规划": "Admission and enrollment planning",
  "梳理成绩、语言、课程体系、专业兴趣、活动经历和家庭目标。": "Review grades, language ability, curriculum, subject interests, activities and family goals.",
  "判断本科直申、副学士衔接、GPA 补强、研究生或多地联申。": "Assess direct undergraduate admission, associate progression, GPA repair, postgraduate or multi-region applications.",
  "建立课程、作业、考试、阅读、科研和导师辅导的持续管理表。": "Build a management table for courses, assignments, exams, reading, research and mentor coaching.",
  "统筹个人陈述、简历、推荐信、作品集、补充材料和申请证据。": "Coordinate personal statements, CVs, recommendation letters, portfolios, supplements and evidence.",
  "管理递交、补件、面试、笔试、跟进和院校沟通节奏。": "Manage submission, supplementary materials, interviews, tests, follow-up and university communication.",
  "比较录取条件、专业路径、入学安排与下一阶段本科/研究生规划。": "Compare offer conditions, subject pathways, enrollment arrangements and the next undergraduate/postgraduate stage.",
  "不只展示录取结果，更展示规划如何改变申请路径": "Not just outcomes, but how planning changes the application pathway",
  "以下案例均采用匿名方式呈现，重点是学生背景、挑战、规划策略与 Rain Education 的关键支持。": "The cases below are anonymized and focus on student background, challenges, planning strategy and Rain Education's key support.",
  "案例筛选": "Case filters",
  "全部案例": "All cases",
  "录取案例": "Admission cases",
  "规划案例": "Planning cases",
  "查看录取案例库": "View admission case library",
  "高考后转向香港副学士，再争取本科衔接": "Turning to a Hong Kong associate degree after Gaokao, then pursuing undergraduate progression",
  "学生希望保留香港本科机会，但直接入读理想本科难度较高。": "The student wanted to keep Hong Kong undergraduate options, but direct entry into an ideal programme was difficult.",
  "学生背景": "Student background",
  "挑战": "Challenge",
  "规划策略": "Planning strategy",
  "阶段成果": "Stage outcome",
  "录取结果": "Admission outcome",
  "最终结果": "Outcome",
  "关键支持": "Key support",
  "高考后家庭希望重新设计香港升学方案。": "After Gaokao, the family wanted to redesign a Hong Kong pathway.",
  "需要兼顾入学可行性、后续 GPA 和本科转入时间线。": "The plan had to balance admission feasibility, later GPA and transfer timing.",
  "副学士申请、选课建议、GPA 管理、本科转入材料提前准备。": "Associate applications, course selection advice, GPA management and early transfer materials.",
  "已建立本科衔接所需的选课、GPA 管理与材料准备节奏，后续结果需以学生表现和当年政策为准。": "Established the course selection, GPA management and materials rhythm needed for undergraduate progression; later outcomes depend on student performance and current policy.",
  "路径判断、学业管理、材料节奏与家长风险沟通。": "Pathway judgement, academic management, material rhythm and parent risk communication.",
  "港科大商业分析硕士申请": "HKUST business analytics master's application",
  "学生需要把商科、数据分析和职业动机整合成有说服力的申请故事。": "The student needed to integrate business, data analytics and career motivation into a convincing application story.",
  "本科阶段具备商科与量化相关经历。": "The student had business and quantitative experience at undergraduate level.",
  "竞争激烈，需要证明量化能力与清晰职业路径。": "Competition was intense, requiring evidence of quantitative ability and a clear career path.",
  "重构项目经历、文书逻辑、简历呈现与港校硕士时间线。": "Restructured project experience, essay logic, CV presentation and the Hong Kong master's timeline.",
  "获得香港科技大学商业分析硕士录取。": "Received admission to HKUST MSc Business Analytics.",
  "材料整合、专业定位和申请节奏管理。": "Material integration, subject positioning and application rhythm management.",
  "英国本科心理学与教育方向录取": "UK undergraduate psychology and education offer",
  "学生需要在 UCAS 材料中清晰呈现心理学兴趣、教育议题和学科准备。": "The student needed to present psychology interests, education issues and subject preparation clearly in UCAS materials.",
  "目标英国高竞争本科方向。": "Targeted a highly competitive UK undergraduate direction.",
  "需要避免文书泛泛而谈，突出学术阅读和长期兴趣。": "The essay needed to avoid generic writing and highlight academic reading and long-term interest.",
  "专业定位、PS 结构优化、材料提交节奏管理。": "Subject positioning, PS structure optimization and submission rhythm management.",
  "获得 UCL 心理学与教育学本科课程无条件录取。": "Received an unconditional place on UCL BSc Psychology with Education.",
  "文书论证、申请节点和多地策略协调。": "Essay argumentation, application milestones and multi-region strategy coordination.",
  "低 GPA 学生的补强与院校梯度重构": "Low-GPA strengthening and university tier reconstruction",
  "学生不是只需要一篇文书，而是需要解释成绩风险并建立补强证据。": "The student needed more than one essay: grade risk explanation and strengthening evidence were required.",
  "本科成绩不占优势，希望申请香港/英国/新加坡研究生。": "The undergraduate GPA was not competitive, while the student hoped to apply for Hong Kong, UK and Singapore postgraduate programmes.",
  "热门专业筛选严格，单一冲刺路径风险高。": "Popular programmes screen strictly, making a single reach path risky.",
  "GPA 诊断、选课建议、实习科研、推荐信和文书解释策略。": "GPA diagnosis, course advice, internships/research, recommendation letters and essay explanation strategy.",
  "建立更合理的申请组合，降低单一路径失败风险。": "Built a more reasonable application portfolio and reduced single-path failure risk.",
  "风险管理、材料重构和备选地区策略。": "Risk management, material restructuring and backup destination strategy.",
  "关于香港升学，家长最常问的五个问题": "Five questions parents most often ask about Hong Kong admissions",
  "副学士是不是正规路径？": "Is an associate degree a legitimate pathway?",
  "香港副学士不是内地大专的简单等同概念，更适合作为本科衔接平台。能否转入理想本科取决于 GPA、专业匹配、材料和当年政策。": "A Hong Kong associate degree is not the same as a mainland junior college qualification. It is better understood as an undergraduate progression platform; transfer depends on GPA, subject fit, materials and current policy.",
  "高考后还有没有香港名校机会？": "Are Hong Kong top university options still possible after Gaokao?",
  "仍需看成绩、英语能力、时间窗口和家庭目标。部分学生可考虑本科直申、副学士、高级文凭或多地联申。": "It depends on grades, English level, timing and family goals. Some students may consider direct undergraduate applications, associate degrees, higher diplomas or multi-region applications.",
  "GPA 低如何规划？": "How should low GPA be planned around?",
  "先判断低 GPA 的原因，再设计课程补强、背景证据、文书解释和院校梯度，避免只靠临时包装。": "First diagnose why the GPA is low, then design course strengthening, profile evidence, essay explanations and university tiers instead of relying on last-minute packaging.",
  "什么时候开始准备？": "When should preparation begin?",
  "越早越能管理 GPA、语言、活动和专业方向；越晚开始，越需要聚焦关键材料和现实可行路径。": "The earlier the start, the more GPA, language, activities and subject direction can be managed; the later the start, the more focused the path must be.",
  "如何判断机构是否靠谱？": "How can families judge whether an agency is reliable?",
  "看是否能讲清楚学生条件、风险、时间线、交付物、服务边界和结果不确定性，而不是只承诺名校。": "Look for whether the team can explain the student's profile, risks, timeline, deliverables, service boundaries and outcome uncertainty, rather than only promising famous universities.",
  "信任来自清晰边界，而不是夸张承诺": "Trust comes from clear boundaries, not exaggerated promises",
  "Rain Education 将咨询评估、服务内容、隐私处理、案例展示和结果边界写入流程，让家庭在每个阶段都知道依据、责任与下一步。": "Rain Education embeds assessment, service scope, privacy handling, case display and outcome boundaries into the process, so families understand the basis, responsibilities and next steps at each stage.",
  "合规说明": "Compliance",
  "服务内容、双方责任、费用与条款以正式协议为准。": "Service scope, responsibilities, fees and terms are subject to the formal agreement.",
  "隐私保护": "Privacy protection",
  "成绩单、文书和个人信息仅用于评估与服务执行。": "Transcripts, essays and personal information are used only for assessment and service delivery.",
  "案例匿名化": "Case anonymization",
  "公开案例移除姓名、申请编号、生日、邮箱、地址、学生 ID 和二维码。": "Public cases remove names, application numbers, birthdays, emails, addresses, student IDs and QR codes.",
  "结果边界": "Outcome boundaries",
  "录取结果受学生背景、申请年份、材料质量和院校政策影响。": "Admissions outcomes depend on student background, application year, material quality and university policies.",
  "由升学顾问与学科导师共同支持每一条升学路径": "Every admissions pathway is supported by advisors and subject mentors together",
  "导师按学科、申请阶段与学生短板匹配，支持 GPA、笔试、面试、作品集、科研写作和长期学术规划。": "Mentors are matched by subject, application stage and student gaps, supporting GPA, tests, interviews, portfolios, research writing and long-term academic planning.",
  "导师方向筛选": "Mentor filters",
  "全部导师": "All mentors",
  "数学 / 物理": "Math / Physics",
  "艺术作品集": "Art portfolio",
  "商科 / 人文": "Business / Humanities",
  "AI / 科研": "AI / Research",
  "服务模块：牛剑数学申请、笔试训练、面试准备": "Modules: Oxbridge mathematics applications, test training and interview preparation",
  "服务模块：大学数学、GPA 管理、研究生申请": "Modules: university mathematics, GPA management and postgraduate applications",
  "服务模块：AI 课程、STEM 学术规划、GPA 支持": "Modules: AI courses, STEM academic planning and GPA support",
  "服务模块：作品集、艺术写作、面试准备": "Modules: portfolio, art writing and interview preparation",
  "服务模块：本科规划、硕博申请、全球升学策略": "Modules: undergraduate planning, postgraduate/doctoral applications and global admissions strategy",
  "服务模块：商科写作、人文学科、副学士支持": "Modules: business writing, humanities and associate degree support",
  "副学士是否等于内地大专？": "Is an associate degree equivalent to a mainland junior college qualification?",
  "不是同一套体系。香港副学士更适合作为本科衔接平台，但能否转入理想本科取决于 GPA、专业匹配、材料和当年招生政策。": "No. They are different systems. A Hong Kong associate degree is better understood as an undergraduate progression platform, with transfer depending on GPA, subject fit, materials and current admission policy.",
  "港九大本硕连读精英规划计划是否承诺录取？": "Does the Hong Kong Nine Universities Bachelor–Master Elite Planning Programme promise admission?",
  "本计划以长期学术规划、过程管理和申请支持为核心，不构成任何院校录取承诺；具体服务与责任边界以正式协议为准。": "This plan centers on long-term academic planning, process management and application support. It does not constitute any university admission promise; service scope and responsibility boundaries are subject to the formal agreement.",
  "高考后多久开始准备香港路径？": "How soon after Gaokao should Hong Kong planning start?",
  "建议越早越好。时间越充足，越能管理英语、GPA、专业选择和本科衔接；时间越紧，越需要聚焦可行路径。": "As early as possible. More time allows English, GPA, subject choice and progression to be managed; a shorter timeline requires a more focused feasible path.",
  "GPA 低还能申请香港或海外硕士吗？": "Can a low-GPA student still apply for Hong Kong or overseas master's programmes?",
  "需要先看低 GPA 的原因、专业匹配、课程难度、背景材料和目标院校梯度，再判断补强方案。": "First review the reasons for the low GPA, subject fit, course difficulty, profile materials and target university tiers, then decide the strengthening plan.",
  "英国 G5 申请是否只看成绩？": "Do UK G5 applications only look at grades?",
  "成绩是基础，但高竞争方向还重视学科深度、阅读、笔试、面试、文书论证和推荐信。": "Grades are the foundation, but competitive subjects also value subject depth, reading, tests, interviews, essay argumentation and recommendation letters.",
  "可以同步申请香港、英国和新加坡吗？": "Can students apply to Hong Kong, the UK and Singapore at the same time?",
  "可以，但需要统筹时间线、材料差异、申请费用和备选逻辑，避免多地申请变成材料混乱。": "Yes, but timelines, material differences, application costs and backup logic must be coordinated to avoid confusion.",
  "导师辅导和顾问服务如何配合？": "How do mentor coaching and advisor services work together?",
  "顾问负责路径设计、申请节奏和家庭沟通；导师围绕学科、GPA、笔试、面试和作品集提供专项支持。": "Advisors handle pathway design, application rhythm and family communication; mentors provide subject, GPA, test, interview and portfolio support.",
  "提交表单后会如何跟进？": "What happens after submitting the form?",
  "Rain Education 顾问会根据学生年级、成绩、目标地区和当前问题进行初步判断，并通过电话、WhatsApp、微信或邮件联系。": "A Rain Education advisor will make an initial assessment based on year level, grades, target destinations and current issues, then contact you by phone, WhatsApp, WeChat or email.",
  "提交学生基本情况，获取初步升学评估": "Submit the student's basic background for an initial admissions assessment",
  "可通过表单、微信、WhatsApp、电话或邮箱联系。学生资料仅用于咨询评估与服务沟通。": "You may contact us by form, WeChat, WhatsApp, phone or email. Student information is used only for consultation assessment and service communication.",
  "香港电话": "Hong Kong phone",
  "内地电话": "Mainland China phone",
  "邮箱": "Email",
  "立即联系": "Contact now",
  "微信": "WeChat",
  "Rain Education 微信二维码": "Rain Education WeChat QR code",
  "Rain Education WhatsApp 二维码": "Rain Education WhatsApp QR code",
  "请勿填写此字段": "Do not fill in this field",
  "学生姓名": "Student name",
  "请输入学生姓名": "Enter student name",
  "联系电话 / WhatsApp / 微信": "Phone / WhatsApp / WeChat",
  "请输入电话、WhatsApp 或微信": "Enter phone, WhatsApp or WeChat",
  "当前阶段": "Current stage",
  "请选择当前阶段": "Select current stage",
  "高考生": "Gaokao student",
  "国际课程学生": "International curriculum student",
  "副学士在读": "Current associate degree student",
  "本科在读": "Current undergraduate",
  "本科毕业": "Undergraduate graduate",
  "低 GPA 学生": "Low-GPA student",
  "目标地区": "Target destination",
  "请选择目标地区": "Select target destination",
  "英国": "United Kingdom",
  "新加坡": "Singapore",
  "美国": "United States",
  "澳洲 / 加拿大": "Australia / Canada",
  "全球名校": "Global top universities",
  "目标项目": "Target programme",
  "请选择目标项目": "Select target programme",
  "首选联系方式": "Preferred contact method",
  "请选择首选联系方式": "Select preferred contact method",
  "电话": "Phone",
  "邮件": "Email",
  "当前成绩 / GPA / 高考预估": "Current grades / GPA / Gaokao estimate",
  "例如：GPA、预估分、语言成绩、目前薄弱科目": "e.g. GPA, predicted score, language result, current weak subjects",
  "备注": "Notes",
  "请简单说明目前情况或目标院校": "Briefly describe the current situation or target universities",
  "我已阅读并同意隐私政策与服务说明，并同意 Rain Education 顾问通过电话、WhatsApp、微信或邮件联系我。": "I have read and agree to the privacy policy and service notes, and agree that a Rain Education advisor may contact me by phone, WhatsApp, WeChat or email.",
  "提交咨询": "Submit enquiry",
  "提交后，Rain Education 顾问将根据你提供的信息进行初步评估。学生信息仅用于咨询评估与服务沟通。结果与服务边界以正式协议为准。": "After submission, a Rain Education advisor will make an initial assessment based on the information provided. Student information is used only for assessment and service communication. Outcomes and service boundaries are subject to the formal agreement.",
  "香港瑞恩国际教育集团有限公司": "Hong Kong Rain International Education Group Limited",
  "规划流程": "Planning process",
  "副学士专题": "Associate degree guide",
  "硕博申请": "Postgraduate applications",
  "案例展示": "Case library",
  "申请指南": "Application guides",
  "预约评估": "Book assessment",
  "隐私政策": "Privacy policy",
  "15年+": "15+ Years",
  "英国 G5": "UK G5",
  "GPA 管理": "GPA Management",
  "香港": "Hong Kong",
  "港八副学士 2+2+1": "HK top-eight associate degree 2+2+1",
  "艺术作品集": "Art portfolio",
  "纯艺方向": "Fine art",
  "数学辅导": "Mathematics tutoring",
  "研究生申请": "Postgraduate applications",
  "AI 教育": "AI education",
  "教育科技": "Education technology",
  "GPA 支持": "GPA support",
  "生物信息": "Bioinformatics",
  "科研写作": "Research writing",
  "商科写作": "Business writing",
  "人文学科": "Humanities",
  "物理方向": "Physics",
  "G5 申请": "G5 applications",
  "科研规划": "Research planning",
  "剑桥数学": "Cambridge mathematics",
  "笔试训练": "Admissions test training",
  "牛剑申请": "Oxbridge applications",
  "全球申请": "Global applications",
  "学术规划": "Academic planning",
  "副学士衔接": "Associate progression",
  "学生辅导": "Student mentoring",
  "具备 Goldsmiths University of London 艺术学习背景，支持作品集评估、个人陈述思路梳理与艺术院校面试准备。": "With an arts background from Goldsmiths University of London, Alison supports portfolio review, personal statement direction and art school interview preparation.",
  "支持 A-Level 数学、大学数学 GPA 管理与研究生申请规划。": "Supports A-Level mathematics, university mathematics GPA management and postgraduate application planning.",
  "具备 HKU 应用人工智能学习背景，关注 AI 素养、教育科技与学生学术规划。": "With applied artificial intelligence training from HKU, Minting focuses on AI literacy, education technology and student academic planning.",
  "围绕生物信息学、环境工程与科研写作方向，支持理科学生进行课程规划、GPA 管理与学术沟通。": "Supports science students in course planning, GPA management and academic communication around bioinformatics, environmental engineering and research writing.",
  "具备 The University of Hong Kong 经济与中文背景，支持商科、人文学科申请与跨文化沟通表达。": "With economics and Chinese studies background from The University of Hong Kong, Ruiyi supports business, humanities and cross-cultural communication.",
  "具备 Imperial College London 物理学习背景，支持物理、数学、科研规划与 G5/HK 院校申请准备。": "With a physics background from Imperial College London, Xiaoyu supports physics, mathematics, research planning and G5/HK applications.",
  "具备 University of Cambridge 数学方向背景，支持牛剑数学申请、笔试训练、面试准备与个人陈述梳理。": "With a mathematics background from the University of Cambridge, Wenhuai supports Oxbridge mathematics applications, test training, interviews and personal statement preparation.",
  "具备 Yale University 教育研究背景，关注学生流动、跨地区申请与长期升学路径规划。": "With an education research background from Yale University, Olivia focuses on student mobility, cross-region applications and long-term progression planning.",
  "具备 UCLA 高等教育方向背景，支持副学士衔接、GPA 恢复、项目选择与跨地区升学规划。": "With a higher education background from UCLA, Sophia supports associate progression, GPA recovery, programme selection and cross-region planning.",
  "香港瑞恩国际教育集团有限公司 HONG KONG RAIN INTERNATIONAL EDUCATION GROUP LIMITED": "Hong Kong Rain International Education Group Limited",
  "Wenhuai Wu 导师照片": "Wenhuai Wu mentor photo",
  "Bodan Ding 导师照片": "Bodan Ding mentor photo",
  "Minting Luo 导师照片": "Minting Luo mentor photo",
  "Alison Ballance 导师照片": "Alison Ballance mentor photo",
  "Qi Miao 导师照片": "Qi Miao mentor photo",
  "Ruiyi Ren 导师照片": "Ruiyi Ren mentor photo",
  "Xiaoyu Sun 导师照片": "Xiaoyu Sun mentor photo",
  "Olivia Zhang 导师照片": "Olivia Zhang mentor photo",
  "Sophia Chen 导师照片": "Sophia Chen mentor photo"
};
const traditionalPhraseMap = {
  "Rain Education": "Rain Education",
  "香港瑞恩国际教育集团有限公司": "香港瑞恩國際教育集團有限公司",
  "香港瑞恩国际教育集团": "香港瑞恩國際教育集團",
  "瑞恩国际": "瑞恩國際",
  "瑞恩书院": "瑞恩書院",
  "港九大本硕连读精英规划计划": "港九大本碩連讀精英規劃計劃",
  "什么": "什麼",
  "怎么": "怎麼",
  "为什么": "為什麼",
  "哪里": "哪裡",
  "不确定性": "不確定性",
  "关注": "關注"
};
const traditionalPostPhraseMap = {
  "專註": "專注",
  "規划": "規劃",
  "計划": "計劃",
  "策划": "策劃",
  "聯系": "聯繫",
  "咨詢": "諮詢",
  "內地": "內地",
  "關註": "關注",
  "確定": "確定",
  "裏程": "里程"
};
const simplifiedToTraditionalMap = {
  "与": "與", "业": "業", "专": "專", "东": "東", "个": "個", "临": "臨", "为": "為", "义": "義",
  "乌": "烏", "乐": "樂", "习": "習", "书": "書", "买": "買", "争": "爭", "于": "於", "云": "雲",
  "亚": "亞", "产": "產", "亩": "畝", "亲": "親", "亿": "億", "仅": "僅", "从": "從", "仓": "倉",
  "仪": "儀", "们": "們", "价": "價", "众": "眾", "优": "優", "会": "會", "传": "傳", "伞": "傘",
  "伟": "偉", "伦": "倫", "伪": "偽", "体": "體", "余": "餘", "佣": "傭", "侠": "俠", "侣": "侶",
  "侥": "僥", "侦": "偵", "侧": "側", "侨": "僑", "侩": "儈", "侪": "儕", "侬": "儂", "俣": "俁",
  "俦": "儔", "俨": "儼", "俩": "倆", "俪": "儷", "俭": "儉", "债": "債", "倾": "傾", "偬": "傯",
  "偻": "僂", "偿": "償", "储": "儲", "儿": "兒", "兑": "兌", "党": "黨", "兰": "蘭", "关": "關",
  "兴": "興", "养": "養", "兽": "獸", "内": "內", "冈": "岡", "册": "冊", "写": "寫", "军": "軍",
  "农": "農", "冯": "馮", "冲": "衝", "决": "決", "况": "況", "冻": "凍", "净": "淨", "准": "準",
  "凉": "涼", "减": "減", "凑": "湊", "几": "幾", "凤": "鳳", "凭": "憑", "凯": "凱", "击": "擊",
  "凿": "鑿", "刘": "劉", "则": "則", "刚": "剛", "创": "創", "删": "刪", "别": "別", "刬": "剗",
  "刭": "剄", "剂": "劑", "剐": "剮", "剑": "劍", "剥": "剝", "剧": "劇", "剩": "剩", "办": "辦",
  "务": "務", "劝": "勸", "动": "動", "励": "勵", "劲": "勁", "劳": "勞", "势": "勢", "勋": "勳",
  "匀": "勻", "区": "區", "医": "醫", "华": "華", "协": "協", "单": "單", "卖": "賣", "卢": "盧",
  "卫": "衛", "却": "卻", "厂": "廠", "厅": "廳", "历": "歷", "厉": "厲", "压": "壓", "厌": "厭",
  "厕": "廁", "厢": "廂", "厦": "廈", "县": "縣", "参": "參", "双": "雙", "发": "發", "变": "變",
  "叙": "敘", "叠": "疊", "叶": "葉", "号": "號", "叹": "嘆", "叽": "嘰", "吁": "籲", "后": "後",
  "向": "向", "吓": "嚇", "吕": "呂", "吗": "嗎", "听": "聽", "启": "啟", "吴": "吳", "呐": "吶",
  "员": "員", "呗": "唄", "呙": "咼", "呛": "嗆", "呜": "嗚", "咏": "詠", "咙": "嚨", "咛": "嚀",
  "咝": "噝", "咤": "吒", "咨": "諮", "咸": "鹹", "响": "響", "哑": "啞", "哒": "噠", "哓": "嘵",
  "哗": "嘩", "哙": "噲", "哜": "嚌", "哝": "噥", "哟": "喲", "唤": "喚", "唬": "嚇", "啧": "嘖",
  "啬": "嗇", "啭": "囀", "啮": "嚙", "啰": "囉", "啸": "嘯", "喷": "噴", "喽": "嘍", "嗫": "囁",
  "嗳": "噯", "嘘": "噓", "嘤": "嚶", "嘱": "囑", "噜": "嚕", "嚣": "囂", "团": "團", "园": "園",
  "围": "圍", "国": "國", "图": "圖", "圆": "圓", "圣": "聖", "场": "場", "坏": "壞", "块": "塊",
  "坚": "堅", "坛": "壇", "坜": "壢", "坝": "壩", "坞": "塢", "坟": "墳", "坠": "墜", "垄": "壟",
  "垅": "壟", "垆": "壚", "垒": "壘", "垦": "墾", "垩": "堊", "垫": "墊", "垭": "埡", "垱": "壋",
  "垲": "塏", "垴": "堖", "埘": "塒", "埙": "塤", "埚": "堝", "埯": "垵", "堑": "塹", "堕": "墮",
  "墙": "牆", "壮": "壯", "声": "聲", "壳": "殼", "处": "處", "备": "備", "复": "複", "够": "夠",
  "头": "頭", "夹": "夾", "夺": "奪", "奋": "奮", "奖": "獎", "奥": "奧", "妆": "妝", "妇": "婦",
  "妈": "媽", "妩": "嫵", "妪": "嫗", "姗": "姍", "姜": "薑", "娱": "娛", "娄": "婁", "娅": "婭",
  "娆": "嬈", "娇": "嬌", "娈": "孌", "娱": "娛", "婴": "嬰", "婵": "嬋", "婶": "嬸", "媪": "媼",
  "嫒": "嬡", "嫔": "嬪", "嫱": "嬙", "嬷": "嬤", "孙": "孫", "学": "學", "孪": "孿", "宁": "寧",
  "宝": "寶", "实": "實", "宠": "寵", "审": "審", "宪": "憲", "宫": "宮", "宽": "寬", "宾": "賓",
  "寝": "寢", "对": "對", "寻": "尋", "导": "導", "寿": "壽", "将": "將", "尔": "爾", "尘": "塵",
  "尝": "嘗", "尧": "堯", "尸": "屍", "尽": "盡", "层": "層", "屉": "屜", "属": "屬", "屡": "屢",
  "岁": "歲", "岂": "豈", "岗": "崗", "岛": "島", "岭": "嶺", "岳": "嶽", "峡": "峽", "峣": "嶢",
  "峤": "嶠", "峥": "崢", "峦": "巒", "崂": "嶗", "崃": "崍", "崄": "嶮", "嵘": "嶸", "嵚": "嶔",
  "巅": "巔", "巩": "鞏", "巯": "巰", "币": "幣", "帅": "帥", "师": "師", "帐": "帳", "帘": "簾",
  "帜": "幟", "带": "帶", "帧": "幀", "帮": "幫", "帱": "幬", "帻": "幘", "帼": "幗", "幂": "冪",
  "庄": "莊", "庆": "慶", "庐": "廬", "库": "庫", "应": "應", "庙": "廟", "庞": "龐", "废": "廢",
  "广": "廣", "开": "開", "异": "異", "弃": "棄", "张": "張", "弥": "彌", "弦": "弦", "弯": "彎",
  "弹": "彈", "强": "強", "归": "歸", "当": "當", "录": "錄", "彝": "彞", "彦": "彥", "彻": "徹",
  "径": "徑", "徕": "徠", "忆": "憶", "忧": "憂", "忾": "愾", "怀": "懷", "态": "態", "怂": "慫",
  "怃": "憮", "怄": "慪", "怅": "悵", "怆": "愴", "怜": "憐", "总": "總", "怼": "懟", "怿": "懌",
  "恋": "戀", "恒": "恆", "恳": "懇", "恶": "惡", "恸": "慟", "恹": "懨", "恺": "愷", "恻": "惻",
  "恼": "惱", "恽": "惲", "悦": "悅", "悬": "懸", "悭": "慳", "悯": "憫", "惊": "驚", "惧": "懼",
  "惨": "慘", "惩": "懲", "惫": "憊", "惬": "愜", "惭": "慚", "惮": "憚", "惯": "慣", "愠": "慍",
  "愤": "憤", "愿": "願", "慑": "懾", "懑": "懣", "懒": "懶", "戆": "戇", "戏": "戲", "战": "戰",
  "户": "戶", "扎": "紮", "扑": "撲", "执": "執", "扩": "擴", "扪": "捫", "扫": "掃", "扬": "揚",
  "扰": "擾", "抚": "撫", "抛": "拋", "抟": "摶", "抠": "摳", "抡": "掄", "抢": "搶", "护": "護",
  "报": "報", "担": "擔", "拟": "擬", "拢": "攏", "拣": "揀", "拥": "擁", "拦": "攔", "拧": "擰",
  "拨": "撥", "择": "擇", "挂": "掛", "挚": "摯", "挛": "攣", "挜": "掗", "挝": "撾", "挞": "撻",
  "挟": "挾", "挠": "撓", "挡": "擋", "挣": "掙", "挤": "擠", "挥": "揮", "挦": "撏", "捞": "撈",
  "损": "損", "捡": "撿", "换": "換", "捣": "搗", "据": "據", "掳": "擄", "掴": "摑", "掷": "擲",
  "掸": "撣", "掺": "摻", "揽": "攬", "揿": "撳", "搀": "攙", "搁": "擱", "搂": "摟", "搅": "攪",
  "携": "攜", "摄": "攝", "摅": "攄", "摆": "擺", "摇": "搖", "摈": "擯", "摊": "攤", "撄": "攖",
  "撑": "撐", "撵": "攆", "撷": "擷", "撸": "擼", "撺": "攛", "擞": "擻", "攒": "攢", "敌": "敵",
  "敛": "斂", "数": "數", "斋": "齋", "斓": "斕", "斗": "鬥", "斩": "斬", "断": "斷", "无": "無",
  "旧": "舊", "时": "時", "旷": "曠", "昆": "崑", "昙": "曇", "昵": "暱", "昼": "晝", "显": "顯",
  "晋": "晉", "晒": "曬", "晓": "曉", "晔": "曄", "晕": "暈", "暂": "暫", "术": "術", "机": "機",
  "杀": "殺", "杂": "雜", "权": "權", "杆": "桿", "条": "條", "来": "來", "杨": "楊", "杰": "傑",
  "极": "極", "构": "構", "枞": "樅", "枢": "樞", "枣": "棗", "枪": "槍", "枫": "楓", "枭": "梟",
  "柜": "櫃", "柠": "檸", "查": "查", "栀": "梔", "栅": "柵", "标": "標", "栈": "棧", "栉": "櫛",
  "栋": "棟", "栌": "櫨", "栎": "櫟", "栏": "欄", "树": "樹", "栖": "棲", "样": "樣", "栾": "欒",
  "桠": "椏", "桡": "橈", "桢": "楨", "档": "檔", "桤": "榿", "桥": "橋", "桦": "樺", "桧": "檜",
  "桨": "槳", "桩": "樁", "梦": "夢", "梼": "檮", "梾": "棶", "检": "檢", "棂": "欞", "椁": "槨",
  "椟": "櫝", "椠": "槧", "椤": "欏", "椭": "橢", "楼": "樓", "榄": "欖", "榇": "櫬", "榈": "櫚",
  "榉": "櫸", "槚": "檟", "槛": "檻", "槟": "檳", "横": "橫", "樯": "檣", "樱": "櫻", "橥": "櫫",
  "橱": "櫥", "橹": "櫓", "橼": "櫞", "檩": "檁", "欢": "歡", "欧": "歐", "歼": "殲", "殁": "歿",
  "残": "殘", "殒": "殞", "殓": "殮", "殚": "殫", "殡": "殯", "殴": "毆", "毁": "毀", "毂": "轂",
  "毕": "畢", "毙": "斃", "毡": "氈", "气": "氣", "氢": "氫", "氩": "氬", "氲": "氳", "汇": "匯",
  "汉": "漢", "汤": "湯", "沟": "溝", "没": "沒", "沣": "灃", "沤": "漚", "沥": "瀝", "沦": "淪",
  "沧": "滄", "沪": "滬", "泞": "濘", "注": "註", "泪": "淚", "泶": "澩", "泷": "瀧", "泸": "瀘",
  "泺": "濼", "泻": "瀉", "泼": "潑", "泽": "澤", "洁": "潔", "洒": "灑", "洼": "窪", "浃": "浹",
  "浅": "淺", "浆": "漿", "浇": "澆", "浈": "湞", "浊": "濁", "测": "測", "济": "濟", "浏": "瀏",
  "浐": "滻", "浑": "渾", "浒": "滸", "浓": "濃", "浔": "潯", "涛": "濤", "涝": "澇", "涞": "淶",
  "涟": "漣", "涠": "潿", "涡": "渦", "涢": "溳", "涣": "渙", "涤": "滌", "润": "潤", "涧": "澗",
  "涨": "漲", "涩": "澀", "渊": "淵", "渌": "淥", "渍": "漬", "渎": "瀆", "渐": "漸", "渑": "澠",
  "渔": "漁", "渖": "瀋", "渗": "滲", "温": "溫", "游": "遊", "湾": "灣", "湿": "濕", "溃": "潰",
  "溅": "濺", "溆": "漵", "滗": "潷", "滚": "滾", "滞": "滯", "滟": "灩", "滠": "灄", "满": "滿",
  "滢": "瀅", "滤": "濾", "滥": "濫", "滦": "灤", "滨": "濱", "滩": "灘", "滪": "澦", "漤": "灠",
  "潆": "瀠", "潇": "瀟", "潋": "瀲", "潍": "濰", "潜": "潛", "潴": "瀦", "澜": "瀾", "濑": "瀨",
  "灏": "灝", "灭": "滅", "灯": "燈", "灵": "靈", "灾": "災", "灿": "燦", "炀": "煬", "炉": "爐",
  "炖": "燉", "炜": "煒", "炝": "熗", "点": "點", "炼": "煉", "炽": "熾", "烁": "爍", "烂": "爛",
  "烃": "烴", "烛": "燭", "烟": "煙", "烦": "煩", "烧": "燒", "烨": "燁", "烩": "燴", "烫": "燙",
  "热": "熱", "焕": "煥", "焖": "燜", "焘": "燾", "煅": "煆", "爱": "愛", "爷": "爺", "牍": "牘",
  "牵": "牽", "牺": "犧", "犊": "犢", "状": "狀", "犷": "獷", "犸": "獁", "犹": "猶", "狈": "狽",
  "狝": "獮", "狞": "獰", "独": "獨", "狭": "狹", "狮": "獅", "狯": "獪", "狰": "猙", "狱": "獄",
  "猎": "獵", "猕": "獼", "猡": "玀", "猪": "豬", "猫": "貓", "献": "獻", "獭": "獺", "玑": "璣",
  "玛": "瑪", "玮": "瑋", "环": "環", "现": "現", "玱": "瑲", "玺": "璽", "珐": "琺", "珑": "瓏",
  "珰": "璫", "珲": "琿", "琏": "璉", "琐": "瑣", "琼": "瓊", "瑶": "瑤", "瑷": "璦", "璎": "瓔",
  "瓒": "瓚", "瓯": "甌", "电": "電", "画": "畫", "畅": "暢", "畴": "疇", "疖": "癤", "疗": "療",
  "疟": "瘧", "疠": "癘", "疡": "瘍", "疬": "癧", "疮": "瘡", "疯": "瘋", "疱": "皰", "疴": "痾",
  "痈": "癰", "痉": "痙", "痒": "癢", "痖": "瘂", "痨": "癆", "痪": "瘓", "痫": "癇", "瘅": "癉",
  "瘗": "瘞", "瘘": "瘻", "瘪": "癟", "瘫": "癱", "瘾": "癮", "瘿": "癭", "癞": "癩", "癣": "癬",
  "皱": "皺", "皲": "皸", "盏": "盞", "盐": "鹽", "监": "監", "盖": "蓋", "盗": "盜", "盘": "盤",
  "眍": "瞘", "眦": "眥", "眬": "矓", "着": "著", "睁": "睜", "睐": "睞", "睑": "瞼", "瞒": "瞞",
  "瞩": "矚", "矫": "矯", "矶": "磯", "矿": "礦", "砀": "碭", "码": "碼", "砖": "磚", "砗": "硨",
  "砚": "硯", "砜": "碸", "砺": "礪", "砻": "礱", "砾": "礫", "础": "礎", "硕": "碩", "硖": "硤",
  "硗": "磽", "硙": "磑", "碍": "礙", "碛": "磧", "碜": "磣", "礼": "禮", "祎": "禕", "祢": "禰",
  "祯": "禎", "祷": "禱", "祸": "禍", "禀": "稟", "禄": "祿", "离": "離", "秃": "禿", "秆": "稈",
  "种": "種", "积": "積", "称": "稱", "秽": "穢", "秾": "穠", "稆": "穭", "税": "稅", "稣": "穌",
  "稳": "穩", "穑": "穡", "穷": "窮", "窃": "竊", "窍": "竅", "窎": "窵", "窑": "窯", "窜": "竄",
  "窝": "窩", "窥": "窺", "窦": "竇", "窭": "窶", "竖": "豎", "竞": "競", "笃": "篤", "笋": "筍",
  "笔": "筆", "笕": "筧", "笺": "箋", "笼": "籠", "笾": "籩", "筑": "築", "筚": "篳", "筛": "篩",
  "筜": "簹", "筝": "箏", "筹": "籌", "签": "簽", "简": "簡", "箓": "籙", "箦": "簀", "箧": "篋",
  "箨": "籜", "箩": "籮", "箪": "簞", "箫": "簫", "篑": "簣", "篮": "籃", "篱": "籬", "簖": "籪",
  "籁": "籟", "籴": "糴", "类": "類", "籼": "秈", "粜": "糶", "粝": "糲", "粤": "粵", "粪": "糞",
  "粮": "糧", "糁": "糝", "糇": "餱", "糌": "糍", "糍": "糍", "糨": "糨", "系": "系", "紧": "緊",
  "絷": "縶", "纟": "糹", "纠": "糾", "纡": "紆", "红": "紅", "纣": "紂", "纤": "纖", "纥": "紇",
  "约": "約", "级": "級", "纨": "紈", "纩": "纊", "纪": "紀", "纫": "紉", "纬": "緯", "纭": "紜",
  "纯": "純", "纰": "紕", "纱": "紗", "纲": "綱", "纳": "納", "纵": "縱", "纶": "綸", "纷": "紛",
  "纸": "紙", "纹": "紋", "纺": "紡", "纽": "紐", "纾": "紓", "线": "線", "绀": "紺", "绁": "紲",
  "绂": "紱", "练": "練", "组": "組", "绅": "紳", "细": "細", "织": "織", "终": "終", "绉": "縐",
  "绊": "絆", "绋": "紼", "绌": "絀", "绍": "紹", "绎": "繹", "经": "經", "绑": "綁", "绒": "絨",
  "结": "結", "绔": "絝", "绕": "繞", "绗": "絎", "绘": "繪", "给": "給", "绚": "絢", "绛": "絳",
  "络": "絡", "绝": "絕", "绞": "絞", "统": "統", "绠": "綆", "绡": "綃", "绢": "絹", "绣": "繡",
  "绥": "綏", "绦": "縧", "继": "繼", "绩": "績", "绪": "緒", "绫": "綾", "续": "續", "绮": "綺",
  "绯": "緋", "绰": "綽", "绱": "緔", "绲": "緄", "绳": "繩", "维": "維", "绵": "綿", "绶": "綬",
  "绷": "繃", "绸": "綢", "绹": "綯", "绺": "綹", "绻": "綣", "综": "綜", "绽": "綻", "绾": "綰",
  "绿": "綠", "缀": "綴", "缁": "緇", "缂": "緙", "缃": "緗", "缄": "緘", "缅": "緬", "缆": "纜",
  "缇": "緹", "缈": "緲", "缉": "緝", "缊": "縕", "缋": "繢", "缌": "緦", "缍": "綞", "缎": "緞",
  "缏": "緶", "缑": "緱", "缒": "縋", "缓": "緩", "缔": "締", "缕": "縷", "编": "編", "缗": "緡",
  "缘": "緣", "缙": "縉", "缚": "縛", "缛": "縟", "缜": "縝", "缝": "縫", "缟": "縞", "缠": "纏",
  "缡": "縭", "缢": "縊", "缣": "縑", "缤": "繽", "缥": "縹", "缦": "縵", "缧": "縲", "缨": "纓",
  "缩": "縮", "缪": "繆", "缫": "繅", "缬": "纈", "缭": "繚", "缮": "繕", "缯": "繒", "缰": "韁",
  "缴": "繳", "缵": "纘", "罂": "罌", "网": "網", "罗": "羅", "罚": "罰", "罢": "罷", "羁": "羈",
  "羟": "羥", "羡": "羨", "翘": "翹", "耸": "聳", "耻": "恥", "聂": "聶", "职": "職", "联": "聯",
  "聩": "聵", "聪": "聰", "肃": "肅", "肠": "腸", "肤": "膚", "肾": "腎", "肿": "腫", "胀": "脹",
  "胁": "脅", "胆": "膽", "胜": "勝", "胧": "朧", "胨": "腖", "胪": "臚", "胫": "脛", "胶": "膠",
  "脉": "脈", "脍": "膾", "脏": "髒", "脑": "腦", "脓": "膿", "脔": "臠", "脚": "腳", "脱": "脫",
  "脸": "臉", "腊": "臘", "腘": "膕", "腻": "膩", "腼": "靦", "腽": "膃", "腾": "騰", "膑": "臏",
  "臜": "臢", "舆": "輿", "舣": "艤", "舰": "艦", "舱": "艙", "舻": "艫", "艰": "艱", "艳": "艷",
  "艺": "藝", "节": "節", "芈": "羋", "芗": "薌", "芜": "蕪", "苁": "蓯", "苇": "葦", "苈": "藶",
  "苋": "莧", "苌": "萇", "苍": "蒼", "苎": "苧", "苏": "蘇", "苹": "蘋", "茎": "莖", "茏": "蘢",
  "茑": "蔦", "茔": "塋", "茕": "煢", "茧": "繭", "荆": "荊", "荐": "薦", "荙": "薘", "荚": "莢",
  "荛": "蕘", "荜": "蓽", "荞": "蕎", "荟": "薈", "荠": "薺", "荡": "蕩", "荣": "榮", "荤": "葷",
  "荥": "滎", "荦": "犖", "荧": "熒", "荨": "蕁", "荩": "藎", "荪": "蓀", "荫": "蔭", "荬": "蕒",
  "荭": "葒", "荮": "葤", "药": "藥", "莅": "蒞", "莱": "萊", "莲": "蓮", "莳": "蒔", "莴": "萵",
  "莶": "薟", "获": "獲", "莸": "蕕", "莹": "瑩", "莺": "鶯", "莼": "蓴", "萝": "蘿", "萤": "螢",
  "营": "營", "萦": "縈", "萧": "蕭", "萨": "薩", "葱": "蔥", "蒇": "蕆", "蒉": "蕢", "蒋": "蔣",
  "蒌": "蔞", "蓝": "藍", "蓟": "薊", "蓠": "蘺", "蓣": "蕷", "蓥": "鎣", "蓦": "驀", "蔷": "薔",
  "蔹": "蘞", "蔺": "藺", "蔼": "藹", "蕰": "薀", "蕲": "蘄", "蕴": "蘊", "薮": "藪", "藓": "蘚",
  "蘖": "櫱", "虏": "虜", "虑": "慮", "虚": "虛", "虫": "蟲", "虬": "虯", "虮": "蟣", "虽": "雖",
  "虾": "蝦", "虿": "蠆", "蚀": "蝕", "蚁": "蟻", "蚂": "螞", "蚕": "蠶", "蚝": "蠔", "蚬": "蜆",
  "蛊": "蠱", "蛎": "蠣", "蛏": "蟶", "蛮": "蠻", "蛰": "蟄", "蛱": "蛺", "蛲": "蟯", "蛳": "螄",
  "蛴": "蠐", "蜕": "蛻", "蜗": "蝸", "蜡": "蠟", "蝇": "蠅", "蝈": "蟈", "蝉": "蟬", "蝼": "螻",
  "蝾": "蠑", "螀": "螿", "螨": "蟎", "蟏": "蠨", "衅": "釁", "衔": "銜", "补": "補", "衬": "襯",
  "衮": "袞", "袄": "襖", "袅": "裊", "袜": "襪", "袭": "襲", "装": "裝", "裆": "襠", "裢": "褳",
  "裣": "襝", "裤": "褲", "裥": "襇", "褛": "褸", "褴": "襤", "见": "見", "观": "觀", "规": "規",
  "觅": "覓", "视": "視", "览": "覽", "觉": "覺", "觊": "覬", "觋": "覡", "觌": "覿", "觎": "覦",
  "觏": "覯", "觐": "覲", "觑": "覷", "觞": "觴", "触": "觸", "觯": "觶", "詟": "讋", "誉": "譽",
  "誊": "謄", "讠": "訁", "计": "計", "订": "訂", "讣": "訃", "认": "認", "讥": "譏", "讦": "訐",
  "讧": "訌", "讨": "討", "让": "讓", "讪": "訕", "讫": "訖", "训": "訓", "议": "議", "讯": "訊",
  "记": "記", "讲": "講", "讳": "諱", "讴": "謳", "讵": "詎", "讶": "訝", "讷": "訥", "许": "許",
  "讹": "訛", "论": "論", "讼": "訟", "讽": "諷", "设": "設", "访": "訪", "诀": "訣", "证": "證",
  "诂": "詁", "诃": "訶", "评": "評", "诅": "詛", "识": "識", "诈": "詐", "诉": "訴", "诊": "診",
  "诋": "詆", "诌": "謅", "词": "詞", "诎": "詘", "诏": "詔", "译": "譯", "诒": "詒", "诓": "誆",
  "诔": "誄", "试": "試", "诖": "詿", "诗": "詩", "诘": "詰", "诙": "詼", "诚": "誠", "诛": "誅",
  "诜": "詵", "话": "話", "诞": "誕", "诟": "詬", "诠": "詮", "诡": "詭", "询": "詢", "诣": "詣",
  "诤": "諍", "该": "該", "详": "詳", "诧": "詫", "诨": "諢", "诩": "詡", "诫": "誡", "诬": "誣",
  "语": "語", "诮": "誚", "误": "誤", "诰": "誥", "诱": "誘", "诲": "誨", "诳": "誑", "说": "說",
  "诵": "誦", "诶": "誒", "请": "請", "诸": "諸", "诹": "諏", "诺": "諾", "读": "讀", "诼": "諑",
  "诽": "誹", "课": "課", "诿": "諉", "谀": "諛", "谁": "誰", "谂": "諗", "调": "調", "谄": "諂",
  "谅": "諒", "谆": "諄", "谈": "談", "谊": "誼", "谋": "謀", "谌": "諶", "谍": "諜", "谎": "謊",
  "谏": "諫", "谐": "諧", "谑": "謔", "谒": "謁", "谓": "謂", "谔": "諤", "谕": "諭", "谖": "諼",
  "谗": "讒", "谘": "諮", "谙": "諳", "谚": "諺", "谛": "諦", "谜": "謎", "谝": "諞", "谟": "謨",
  "谠": "讜", "谡": "謖", "谢": "謝", "谣": "謠", "谤": "謗", "谥": "謚", "谦": "謙", "谧": "謐",
  "谨": "謹", "谩": "謾", "谪": "謫", "谫": "譾", "谬": "謬", "谭": "譚", "谮": "譖", "谯": "譙",
  "谱": "譜", "谲": "譎", "谳": "讞", "谴": "譴", "谵": "譫", "谶": "讖", "谷": "谷", "豮": "豶",
  "贝": "貝", "负": "負", "贡": "貢", "财": "財", "责": "責", "贤": "賢", "败": "敗", "账": "賬",
  "货": "貨", "质": "質", "贩": "販", "贪": "貪", "贫": "貧", "贬": "貶", "购": "購", "贮": "貯",
  "贯": "貫", "贰": "貳", "贱": "賤", "贲": "賁", "贳": "貰", "贴": "貼", "贵": "貴", "贶": "貺",
  "贷": "貸", "贸": "貿", "费": "費", "贺": "賀", "贻": "貽", "贼": "賊", "贽": "贄", "贾": "賈",
  "贿": "賄", "赀": "貲", "赁": "賃", "赂": "賂", "赃": "贓", "资": "資", "赅": "賅", "赆": "贐",
  "赇": "賕", "赈": "賑", "赉": "賚", "赊": "賒", "赋": "賦", "赌": "賭", "赍": "齎", "赎": "贖",
  "赏": "賞", "赐": "賜", "赑": "贔", "赒": "賙", "赓": "賡", "赔": "賠", "赕": "賧", "赖": "賴",
  "赗": "賵", "赘": "贅", "赙": "賻", "赚": "賺", "赛": "賽", "赜": "賾", "赝": "贗", "赞": "讚",
  "赠": "贈", "赡": "贍", "赢": "贏", "赣": "贛", "赵": "趙", "赶": "趕", "趋": "趨", "趱": "趲",
  "趸": "躉", "跃": "躍", "跄": "蹌", "跞": "躒", "践": "踐", "跶": "躂", "跷": "蹺", "跸": "蹕",
  "跹": "躚", "跻": "躋", "踊": "踴", "踌": "躊", "踪": "蹤", "踬": "躓", "踯": "躑", "蹑": "躡",
  "蹒": "蹣", "蹰": "躕", "蹿": "躥", "躏": "躪", "躜": "躦", "躯": "軀", "车": "車", "轧": "軋",
  "轨": "軌", "轩": "軒", "轫": "軔", "转": "轉", "轭": "軛", "轮": "輪", "软": "軟", "轰": "轟",
  "轱": "軲", "轲": "軻", "轳": "轤", "轴": "軸", "轵": "軹", "轶": "軼", "轷": "軤", "轸": "軫",
  "轹": "轢", "轺": "軺", "轻": "輕", "轼": "軾", "载": "載", "轾": "輊", "轿": "轎", "辀": "輈",
  "辁": "輇", "辂": "輅", "较": "較", "辄": "輒", "辅": "輔", "辆": "輛", "辇": "輦", "辈": "輩",
  "辉": "輝", "辊": "輥", "辋": "輞", "辍": "輟", "辎": "輜", "辏": "輳", "辐": "輻", "辑": "輯",
  "输": "輸", "辔": "轡", "辖": "轄", "辗": "輾", "辘": "轆", "辙": "轍", "辚": "轔", "辞": "辭",
  "辩": "辯", "辫": "辮", "边": "邊", "辽": "遼", "达": "達", "迁": "遷", "过": "過", "迈": "邁",
  "运": "運", "还": "還", "这": "這", "进": "進", "远": "遠", "违": "違", "连": "連", "迟": "遲",
  "迩": "邇", "迳": "逕", "迹": "跡", "适": "適", "选": "選", "逊": "遜", "递": "遞", "逻": "邏",
  "遗": "遺", "遥": "遙", "邓": "鄧", "邝": "鄺", "邬": "鄔", "邮": "郵", "邹": "鄒", "邺": "鄴",
  "邻": "鄰", "郁": "鬱", "郄": "郤", "郏": "郟", "郐": "鄶", "郑": "鄭", "郓": "鄆", "郦": "酈",
  "郧": "鄖", "郸": "鄲", "酝": "醞", "酦": "醱", "酱": "醬", "酽": "釅", "酾": "釃", "酿": "釀",
  "释": "釋", "里": "裏", "鉴": "鑒", "銮": "鑾", "针": "針", "钉": "釘", "钊": "釗", "钋": "釙",
  "钌": "釕", "钍": "釷", "钎": "釺", "钏": "釧", "钐": "釤", "钑": "鈒", "钒": "釩", "钓": "釣",
  "钔": "鍆", "钕": "釹", "钖": "鍚", "钗": "釵", "钘": "鈃", "钙": "鈣", "钚": "鈈", "钛": "鈦",
  "钜": "鉅", "钝": "鈍", "钞": "鈔", "钟": "鐘", "钠": "鈉", "钡": "鋇", "钢": "鋼", "钣": "鈑",
  "钤": "鈐", "钥": "鑰", "钦": "欽", "钧": "鈞", "钨": "鎢", "钩": "鉤", "钪": "鈧", "钫": "鈁",
  "钬": "鈥", "钭": "鈄", "钮": "鈕", "钯": "鈀", "钰": "鈺", "钱": "錢", "钲": "鉦", "钳": "鉗",
  "钴": "鈷", "钵": "缽", "钶": "鈳", "钷": "鉕", "钸": "鈽", "钹": "鈸", "钺": "鉞", "钻": "鑽",
  "钼": "鉬", "钽": "鉭", "钾": "鉀", "钿": "鈿", "铀": "鈾", "铁": "鐵", "铂": "鉑", "铃": "鈴",
  "铄": "鑠", "铅": "鉛", "铆": "鉚", "铈": "鈰", "铉": "鉉", "铊": "鉈", "铋": "鉍", "铌": "鈮",
  "铍": "鈹", "铎": "鐸", "铐": "銬", "铑": "銠", "铒": "鉺", "铓": "鋩", "铔": "錏", "铕": "銪",
  "铖": "鋮", "铗": "鋏", "铘": "鋣", "铙": "鐃", "铚": "銍", "铛": "鐺", "铜": "銅", "铝": "鋁",
  "铞": "銱", "铟": "銦", "铠": "鎧", "铡": "鍘", "铢": "銖", "铣": "銑", "铤": "鋌", "铥": "銩",
  "铦": "銛", "铧": "鏵", "铨": "銓", "铩": "鎩", "铪": "鉿", "铫": "銚", "铬": "鉻", "铭": "銘",
  "铮": "錚", "铯": "銫", "铰": "鉸", "铱": "銥", "铲": "鏟", "铳": "銃", "铴": "鐋", "铵": "銨",
  "银": "銀", "铷": "銣", "铸": "鑄", "铹": "鐒", "铺": "鋪", "铻": "鋙", "铼": "錸", "铽": "鋱",
  "链": "鏈", "铿": "鏗", "销": "銷", "锁": "鎖", "锂": "鋰", "锃": "鋥", "锄": "鋤", "锅": "鍋",
  "锆": "鋯", "锇": "鋨", "锈": "鏽", "锉": "銼", "锊": "鋝", "锋": "鋒", "锌": "鋅", "锍": "鋶",
  "锎": "鐦", "锏": "鐧", "锐": "銳", "锑": "銻", "锒": "鋃", "锓": "鋟", "锔": "鋦", "锕": "錒",
  "锖": "錆", "锗": "鍺", "锘": "鍩", "错": "錯", "锚": "錨", "锛": "錛", "锜": "錡", "锝": "鍀",
  "锞": "錁", "锟": "錕", "锡": "錫", "锢": "錮", "锣": "鑼", "锤": "錘", "锥": "錐", "锦": "錦",
  "锧": "鑕", "锨": "鍁", "锩": "錈", "锪": "鍃", "锫": "錇", "锬": "錟", "锭": "錠", "键": "鍵",
  "锯": "鋸", "锰": "錳", "锱": "錙", "锲": "鍥", "锴": "鍇", "锵": "鏘", "锶": "鍶", "锷": "鍔",
  "锸": "鍤", "锹": "鍬", "锺": "鍾", "锻": "鍛", "锼": "鎪", "锽": "鍠", "锾": "鍰", "锿": "鎄",
  "镀": "鍍", "镁": "鎂", "镂": "鏤", "镃": "鎡", "镄": "鐨", "镅": "鎇", "镆": "鏌", "镇": "鎮",
  "镈": "鎛", "镉": "鎘", "镊": "鑷", "镋": "钂", "镌": "鐫", "镍": "鎳", "镎": "鎿", "镏": "鎦",
  "镐": "鎬", "镑": "鎊", "镒": "鎰", "镓": "鎵", "镔": "鑌", "镕": "鎔", "镖": "鏢", "镗": "鏜",
  "镘": "鏝", "镙": "鏍", "镚": "鏰", "镛": "鏞", "镜": "鏡", "镝": "鏑", "镞": "鏃", "镟": "鏇",
  "镠": "鏐", "镡": "鐔", "镢": "钁", "镣": "鐐", "镤": "鏷", "镥": "鑥", "镦": "鐓", "镧": "鑭",
  "镨": "鐠", "镩": "鑹", "镪": "鏹", "镫": "鐙", "镬": "鑊", "镭": "鐳", "镮": "鐶", "镯": "鐲",
  "镰": "鐮", "镱": "鐿", "镲": "鑔", "镳": "鑣", "镴": "鑞", "镶": "鑲", "长": "長", "门": "門",
  "闩": "閂", "闪": "閃", "闫": "閆", "闭": "閉", "问": "問", "闯": "闖", "闰": "閏", "闱": "闈",
  "闲": "閒", "间": "間", "闵": "閔", "闶": "閌", "闷": "悶", "闸": "閘", "闹": "鬧", "闺": "閨",
  "闻": "聞", "闼": "闥", "闽": "閩", "闾": "閭", "阀": "閥", "阁": "閣", "阂": "閡", "阃": "閫",
  "阄": "鬮", "阅": "閱", "阆": "閬", "阇": "闍", "阈": "閾", "阉": "閹", "阊": "閶", "阋": "鬩",
  "阌": "閿", "阍": "閽", "阎": "閻", "阏": "閼", "阐": "闡", "阑": "闌", "阒": "闃", "阔": "闊",
  "阕": "闋", "阖": "闔", "阗": "闐", "阙": "闕", "阚": "闞", "队": "隊", "阳": "陽", "阴": "陰",
  "阵": "陣", "阶": "階", "际": "際", "陆": "陸", "陇": "隴", "陈": "陳", "陉": "陘", "陕": "陝",
  "陧": "隉", "陨": "隕", "险": "險", "随": "隨", "隐": "隱", "隶": "隸", "隽": "雋", "难": "難",
  "雏": "雛", "雠": "讎", "雳": "靂", "雾": "霧", "霁": "霽", "霉": "霉", "静": "靜", "靥": "靨",
  "鞑": "韃", "鞒": "鞽", "鞯": "韉", "韦": "韋", "韧": "韌", "韨": "韍", "韩": "韓", "韪": "韙",
  "韫": "韞", "韬": "韜", "韵": "韻", "页": "頁", "顶": "頂", "顷": "頃", "项": "項", "顺": "順",
  "须": "須", "顼": "頊", "顽": "頑", "顾": "顧", "顿": "頓", "颀": "頎", "颁": "頒", "颂": "頌",
  "预": "預", "颅": "顱", "领": "領", "颇": "頗", "颈": "頸", "颉": "頡", "颊": "頰", "颋": "頲",
  "颌": "頜", "颍": "潁", "颎": "熲", "颏": "頦", "颐": "頤", "频": "頻", "颓": "頹", "颔": "頷",
  "颖": "穎", "颗": "顆", "题": "題", "颚": "顎", "颛": "顓", "颜": "顏", "额": "額", "颞": "顳",
  "颟": "顢", "颠": "顛", "颡": "顙", "颢": "顥", "颤": "顫", "颥": "顬", "颦": "顰", "颧": "顴",
  "风": "風", "飒": "颯", "飓": "颶", "飕": "颼", "飘": "飄", "飙": "飆", "飚": "飆", "飞": "飛",
  "飨": "饗", "餍": "饜", "饣": "飠", "饥": "饑", "饧": "餳", "饨": "飩", "饩": "餼", "饪": "飪",
  "饫": "飫", "饬": "飭", "饭": "飯", "饮": "飲", "饯": "餞", "饰": "飾", "饱": "飽", "饲": "飼",
  "饳": "飿", "饴": "飴", "饵": "餌", "饶": "饒", "饷": "餉", "饸": "餄", "饹": "餎", "饺": "餃",
  "饻": "餏", "饼": "餅", "饽": "餑", "饿": "餓", "馀": "餘", "馁": "餒", "馂": "餕", "馃": "餜",
  "馄": "餛", "馅": "餡", "馆": "館", "馇": "餷", "馈": "饋", "馊": "餿", "馋": "饞", "馍": "饃",
  "馎": "餺", "馏": "餾", "馐": "饈", "馑": "饉", "馒": "饅", "馓": "饊", "馔": "饌", "馕": "饢",
  "马": "馬", "驭": "馭", "驮": "馱", "驯": "馴", "驰": "馳", "驱": "驅", "驲": "馹", "驳": "駁",
  "驴": "驢", "驵": "駔", "驶": "駛", "驷": "駟", "驸": "駙", "驹": "駒", "驺": "騶", "驻": "駐",
  "驼": "駝", "驽": "駑", "驾": "駕", "驿": "驛", "骀": "駘", "骁": "驍", "骂": "罵", "骄": "驕",
  "骅": "驊", "骆": "駱", "骇": "駭", "骈": "駢", "骊": "驪", "骋": "騁", "验": "驗", "骏": "駿",
  "骐": "騏", "骑": "騎", "骒": "騍", "骓": "騅", "骖": "驂", "骗": "騙", "骘": "騭", "骚": "騷",
  "骛": "騖", "骜": "驁", "骝": "騮", "骟": "騸", "骠": "驃", "骡": "騾", "骢": "驄", "骣": "驏",
  "骤": "驟", "骥": "驥", "骧": "驤", "髅": "髏", "髋": "髖", "髌": "髕", "鬓": "鬢", "魇": "魘",
  "魉": "魎", "鱼": "魚", "鱿": "魷", "鲁": "魯", "鲂": "魴", "鲅": "鮁", "鲆": "鮃", "鲇": "鯰",
  "鲈": "鱸", "鲉": "鮋", "鲊": "鮓", "鲋": "鮒", "鲌": "鮊", "鲍": "鮑", "鲎": "鱟", "鲏": "鮍",
  "鲐": "鮐", "鲑": "鮭", "鲒": "鮚", "鲔": "鮪", "鲕": "鮞", "鲖": "鮦", "鲗": "鰂", "鲘": "鮜",
  "鲙": "鱠", "鲚": "鱭", "鲛": "鮫", "鲜": "鮮", "鲝": "鮺", "鲞": "鯗", "鲟": "鱘", "鲠": "鯁",
  "鲡": "鱺", "鲢": "鰱", "鲣": "鰹", "鲤": "鯉", "鲥": "鰣", "鲦": "鰷", "鲧": "鯀", "鲨": "鯊",
  "鲩": "鯇", "鲫": "鯽", "鲭": "鯖", "鲮": "鯪", "鲰": "鯫", "鲱": "鯡", "鲲": "鯤", "鲳": "鯧",
  "鲴": "鯝", "鲵": "鯢", "鲶": "鯰", "鲷": "鯛", "鲸": "鯨", "鲺": "鯴", "鲻": "鯔", "鲼": "鱝",
  "鲽": "鰈", "鳄": "鱷", "鳅": "鰍", "鳆": "鰒", "鳇": "鰉", "鳌": "鰲", "鳍": "鰭", "鳎": "鰨",
  "鳏": "鰥", "鳐": "鰩", "鳓": "鰳", "鳔": "鰾", "鳕": "鱈", "鳖": "鱉", "鳗": "鰻", "鳘": "鰵",
  "鳙": "鱅", "鳜": "鱖", "鳝": "鱔", "鳞": "鱗", "鳟": "鱒", "鳢": "鱧", "鸟": "鳥", "鸠": "鳩",
  "鸡": "雞", "鸢": "鳶", "鸣": "鳴", "鸥": "鷗", "鸦": "鴉", "鸧": "鶬", "鸨": "鴇", "鸩": "鴆",
  "鸪": "鴣", "鸫": "鶇", "鸬": "鸕", "鸭": "鴨", "鸮": "鴞", "鸯": "鴦", "鸰": "鴒", "鸱": "鴟",
  "鸲": "鴝", "鸳": "鴛", "鸴": "鷽", "鸵": "鴕", "鸶": "鷥", "鸷": "鷙", "鸸": "鴯", "鸹": "鴰",
  "鸺": "鵂", "鸻": "鴴", "鸼": "鵃", "鸽": "鴿", "鸾": "鸞", "鸿": "鴻", "鹁": "鵓", "鹂": "鸝",
  "鹃": "鵑", "鹄": "鵠", "鹅": "鵝", "鹆": "鵒", "鹇": "鷳", "鹈": "鵜", "鹉": "鵡", "鹊": "鵲",
  "鹋": "鶓", "鹌": "鵪", "鹍": "鵾", "鹏": "鵬", "鹐": "鵮", "鹑": "鶉", "鹒": "鶊", "鹓": "鵷",
  "鹕": "鶘", "鹖": "鶡", "鹗": "鶚", "鹘": "鶻", "鹙": "鶖", "鹚": "鶿", "鹛": "鶥", "鹜": "鶩",
  "鹝": "鷊", "鹞": "鷂", "鹟": "鶲", "鹠": "鶹", "鹡": "鶺", "鹣": "鶼", "鹤": "鶴", "鹦": "鸚",
  "鹧": "鷓", "鹨": "鷚", "鹩": "鷯", "鹪": "鷦", "鹫": "鷲", "鹬": "鷸", "鹭": "鷺", "鹰": "鷹",
  "鹳": "鸛", "麦": "麥", "麸": "麩", "黄": "黃", "黉": "黌", "齐": "齊", "齑": "齏", "齿": "齒",
  "龀": "齔", "龁": "齕", "龂": "齗", "龃": "齟", "龄": "齡", "龅": "齙", "龆": "齠", "龇": "齜",
  "龈": "齦", "龉": "齬", "龊": "齪", "龋": "齲", "龌": "齷", "龙": "龍", "龚": "龔", "龛": "龕"
};
function toTraditional(text) {
  let converted = text;
  Object.keys(traditionalPhraseMap).forEach(function (key) {
    converted = converted.split(key).join(traditionalPhraseMap[key]);
  });
  converted = Array.from(converted).map(function (char) {
    return simplifiedToTraditionalMap[char] || char;
  }).join("");
  return converted.replace(/專註|規划|計划|策划|聯系|咨詢|內地|關註|確定|裏程/g, function (match) {
    return traditionalPostPhraseMap[match] || match;
  });
}
function normalize(value) {
  return value.trim().replace(/\s+/g, " ");
}
function translateEnglish(text) {
  if (!/[\u4e00-\u9fff]/.test(text)) return text;
  return englishTextMap[text] || "Rain Education advisory content";
}
function translateValue(value, language) {
  if (!value || !value.trim()) return value;
  const leading = value.match(/^\s*/)[0];
  const trailing = value.match(/\s*$/)[0];
  const core = normalize(value);
  let translated = core;
  if (language === "zh-HK") translated = toTraditional(core);
  if (language === "en") translated = translateEnglish(core);
  return leading + translated + trailing;
}
const translatableTextNodes = [];
const translatableAttributes = [];
function shouldSkip(node) {
  const parent = node.nodeType === Node.TEXT_NODE ? node.parentElement : node;
  return !parent || Boolean(parent.closest("script, style, [data-no-translate]"));
}
function collectTranslatableContent() {
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let current = walker.nextNode();
  while (current) {
    if (!shouldSkip(current) && current.nodeValue.trim()) {
      translatableTextNodes.push({ node: current, original: current.nodeValue });
    }
    current = walker.nextNode();
  }
  document.querySelectorAll("[placeholder], [aria-label], [alt], [title]").forEach(function (element) {
    if (shouldSkip(element)) return;
    ["placeholder", "aria-label", "alt", "title"].forEach(function (attribute) {
      if (element.hasAttribute(attribute)) {
        translatableAttributes.push({ element: element, attribute: attribute, original: element.getAttribute(attribute) });
      }
    });
  });
}
function setLanguage(language) {
  document.documentElement.lang = language === "en" ? "en" : language === "zh-HK" ? "zh-Hant-HK" : "zh-CN";
  document.body.dataset.language = language;
  localStorage.setItem("rainEducationLanguage", language);
  translatableTextNodes.forEach(function (item) { item.node.nodeValue = translateValue(item.original, language); });
  translatableAttributes.forEach(function (item) { item.element.setAttribute(item.attribute, translateValue(item.original, language)); });
  languageButtons.forEach(function (button) { button.classList.toggle("is-active", button.dataset.langSwitch === language); });
  if (formLanguage) formLanguage.value = language;
}
function updateConsultationMeta() {
  if (formPageUrl) formPageUrl.value = window.location.href;
  if (formLanguage) formLanguage.value = document.body.dataset.language || "zh-CN";
}
if (menuToggle && navLinks) {
  menuToggle.addEventListener("click", function () {
    const open = navLinks.classList.toggle("is-open");
    menuToggle.setAttribute("aria-expanded", String(open));
  });
  navLinks.querySelectorAll("a").forEach(function (link) {
    link.addEventListener("click", function () {
      navLinks.classList.remove("is-open");
      menuToggle.setAttribute("aria-expanded", "false");
    });
  });
}
caseFilterButtons.forEach(function (button) {
  button.addEventListener("click", function () {
    const filter = button.dataset.filter;
    caseFilterButtons.forEach(function (item) { item.classList.toggle("is-active", item === button); });
    document.querySelectorAll(".case-card").forEach(function (card) {
      const categories = (card.dataset.category || "").split(/\s+/);
      card.classList.toggle("is-hidden", filter !== "all" && !categories.includes(filter));
    });
  });
});
mentorFilterButtons.forEach(function (button) {
  button.addEventListener("click", function () {
    const filter = button.dataset.mentorFilter;
    mentorFilterButtons.forEach(function (item) { item.classList.toggle("is-active", item === button); });
    document.querySelectorAll(".mentor-card").forEach(function (card) {
      const categories = (card.dataset.mentorCategory || "").split(/\s+/);
      card.classList.toggle("is-hidden", filter !== "all" && !categories.includes(filter));
    });
  });
});
languageButtons.forEach(function (button) {
  button.addEventListener("click", function () { setLanguage(button.dataset.langSwitch); });
});
if (consultationForm) {
  consultationForm.addEventListener("submit", updateConsultationMeta);
  if (formMessage && consultationForm.dataset.nativeSubmit !== "true") {
    consultationForm.addEventListener("submit", function (event) {
      event.preventDefault();
      updateConsultationMeta();
      formMessage.textContent = translateValue("提交后，Rain Education 顾问将根据你提供的信息进行初步评估。", document.body.dataset.language || "zh-CN");
      formMessage.classList.add("is-visible");
    });
  }
}
collectTranslatableContent();
const savedLanguage = localStorage.getItem("rainEducationLanguage");
const urlLanguage = new URLSearchParams(window.location.search).get("lang");
setLanguage(urlLanguage || savedLanguage || "zh-CN");
updateConsultationMeta();
